---
- name: installing required packages
  apt: pkg=zsh state=latest

- name: placing .z files
  copy: src={{ item }} dest=/home/{{ r_user}}  mode=0644 owner={{ r_user }} group={{ r_group }} force=no
  with_items:
    - .zaliasses
    - .zcolors
    - .zcompdump
    - .zfunctions
    - .zprompt
    - .zshrc

- name: changing usershell to zsh
  user: name={{ r_user }} shell=/usr/bin/zsh
