---
- name: ensure fail2ban is installed
  apt: name=fail2ban state=latest update_cache=true cache_valid_time=86400
  notify:
    - restart fail2ban

- name: ensure fail2ban configuration is managed
  template: src={{ item }}.j2 dest=/etc/fail2ban/{{ item }}
  with_items:
    - jail.local
    - fail2ban.local
  notify:
    - restart fail2ban

- name: ensure fail2ban is running and enabled
  service: name=fail2ban state=started enabled=true
