---
- name: ensure monit is installed
  apt: name=monit state=latest update_cache=true cache_valid_time=86400
  notify:
    - restart monit

- name: ensure monit configuration is managed
  template: src=monitrc.j2 dest=/etc/monit/monitrc
  notify:
    - reload monit

- name: ensure monit process configuration is removed
  file: path=/etc/monit/conf.d/{{ item.type|default("base") }}_{{ item.process }}.conf state=absent
  with_flattened:
    - monit_process_list
    - monit_process_group_list
    - monit_process_host_list
  when: ((item.type|default("base") is defined and item.type|default("base")) and (item.process is defined and item.process) and (item.pid_path is defined and item.pid_path)) and (item.delete is defined and item.delete)
  notify:
    - reload monit

- name: ensure monit process configuration is added
  template: src=conf.d/{{ item.type|default("base") }}.conf.j2 dest=/etc/monit/conf.d/{{ item.type|default("base") }}_{{ item.process }}.conf
  with_flattened:
    - monit_process_list
    - monit_process_group_list
    - monit_process_host_list
  when: (item.type|default("base") is defined and item.type|default("base") and item.process is defined and item.process and item.pid_path is defined and item.pid_path) and (item.delete is undefined or (item.delete is defined and not item.delete))
  notify:
    - reload monit

- name: ensure monit pam is copied
  copy: src={{ monit_http_local_pemfile_path }} dest=/etc/monit/monit.pem mode=0600
  when: monit_http_ssl
  notify:
    - restart monit

- name: ensure monit is started and enabled
  service: name=monit state=started enabled=true
