---
openssh_server_settings:
  Port: "22"
  AddressFamily: "any"
  Protocol: "2"
  UsePrivilegeSeparation: "yes"
  KeyRegenerationInterval: "3600"
  ServerKeyBits: "1024"
  SyslogFacility: "AUTH"
  LogLevel: "INFO"
  LoginGraceTime: "120"
  PermitRootLogin: "no"
  StrictModes: "yes"
  MaxAuthTries: "6"
  MaxSessions: "10"
  RSAAuthentication: "yes"
  PubkeyAuthentication: "yes"
  AuthorizedKeysFile: "%h/.ssh/authorized_keys"
  IgnoreRhosts: "yes"
  RhostsRSAAuthentication: "no"
  HostbasedAuthentication: "no"
  IgnoreUserKnownHosts: "no"
  PermitEmptyPasswords: "no"
  ChallengeResponseAuthentication: "no"
  PasswordAuthentication: "no"
  KerberosAuthentication: "no"
  KerberosGetAFSToken: "no"
  KerberosOrLocalPasswd: "yes"
  KerberosTicketCleanup: "yes"
  GSSAPIAuthentication: "no"
  GSSAPICleanupCredentials: "yes"
  X11Forwarding: "yes"
  X11DisplayOffset: "10"
  X11UseLocalhost: "yes"
  PrintMotd: "no"
  PrintLastLog: "yes"
  TCPKeepAlive: "yes"
  UseLogin: "no"
  MaxStartups: "10:30:100"
  Banner: "none"
  AcceptEnv: "LANG LC_*"
  Subsystem: "sftp /usr/lib/openssh/sftp-server"
  UsePAM: "yes"
  UseDNS: "no"
  AllowAgentForwarding: "yes"
  AllowTcpForwarding: "yes"
  GatewayPorts: "no"
  ClientAliveInterval: "1750"
  ClientAliveCountMax: "0"
  PermitUserEnvironment: "no"
  Compression: "delayed"
  PidFile: "/var/run/sshd.pid"
  ChrootDirectory: "none"
